export const phoneBook = [
  { name: 'Тимур', lastName: 'Шаов' },
  { name: 'Алина', lastName: 'Бокова' },
  { name: 'Юрий', lastName: 'Дудь' },
  { name: 'Станислав', lastName: 'Бахвалов' },
  { name: 'Михаил', lastName: 'Сидоров' },
  { name: 'Ирина', lastName: 'Хакамада' },
  { name: 'Анастасия', lastName: 'Стоцкая' },
  { name: 'Антон', lastName: 'Долин' },
  { name: 'Иван', lastName: 'Поддубный'},
  { name: 'Юрий', lastName: 'Анисимов' },
  { name: 'Михаил', lastName: 'Пивоваров' },
  { name: 'Светлана', lastName: 'Баранова' },
  { name: 'Кристина', lastName: 'Романова' },
  { name: 'Александр', lastName: 'Первый' },
  { name: 'Сергей', lastName: 'Тарасенко' },
  { name: 'Иван', lastName: 'Шаров' },
  { name: 'Ася', lastName: 'Белкова' },
  { name: 'Юрий', lastName: 'Антонов' },
  { name: 'Александр', lastName: 'Бархатов' },
  { name: 'Михаил', lastName: 'Разговоров' },
  { name: 'Ирина', lastName: 'Сидоренко' },
  { name: 'Анастасия', lastName: 'Стоцкая' },
  { name: 'Иван', lastName: 'Дулин' },
  { name: 'Иван', lastName: 'Царевич'},
  { name: 'Никита', lastName: 'Анисимов' },
  { name: 'Артем', lastName: 'Пивоваров' },
  { name: 'Светлана', lastName: 'Коновалова' },
  { name: 'Кристина', lastName: 'Романова' },
  { name: 'Александр', lastName: 'Второй' }
]

export const cars = [
  { make: 'Mazda', color: 'Белый', race: 1524 },
  { make: 'BMW', color: 'Красный', race: 95844 },
  { make: 'Audi', color: 'Черный', race: 135000 },
  { make: 'VW', color: 'Зеленый', race: 96254 },
  { make: 'Volvo', color: 'Синий', race: 0 },
  { make: 'Volvo', color: 'Красный', race: 10000 },
  { make: 'Range Rover', color: 'Белый', race: 48657 },
  { make: 'Mersedes', color: 'Желтый', race: 10000 },
  { make: 'KIA', color: 'Черный', race: 9524 },
  { make: 'Subaru', color: 'Желтый', race: 1500},
  { make: 'Mazda', color: 'Зеленый', race: 40125},
  { make: 'Opel', color: 'Синий', race: 5842 },
  { make: 'Opel', color: 'Белый', race: 55300 },
  { make: 'BMW', color: 'Красный', race: 1008 },
  { make: 'Audi', color: 'Черный', race: 1000 }
]

export const people = [
  { name: 'Сергей', secondName: 'Владимирович', lastName: 'Тарасенко', age: 39},
  { name: 'Сергей', secondName: 'Владимирович', lastName: 'Тарасенко', age: 39},
  { name: 'Михаил', secondName: 'Владимирович', lastName: 'Антонов', age: 39},
  { name: 'Иван', secondName: 'Иванович', lastName: 'Поддубный', age: 30},
  { name: 'Артем', secondName: 'Сергеевич', lastName: 'Кириллов', age: 2},
  { name: 'Артем', secondName: 'Петрович', lastName: 'Иванов', age: 29},
  { name: 'Светлана', secondName: 'Игоревна', lastName: 'Мурашова', age: 43},
  { name: 'Светлана', secondName: 'Алексеевна', lastName: 'Анисимова', age: 43},
  { name: 'Артем', secondName: 'Петрович', lastName: 'Семин', age: 29},
  { name: 'Анатолий', secondName: 'Сергеевич', lastName: 'Тарасов', age: 38},
  { name: 'Михаил', secondName: 'Владимирович', lastName: 'Громов', age: 39},
  { name: 'Иван', secondName: 'Иванович', lastName: 'Сидоров', age: 30},
  { name: 'Станислав', secondName: 'Сергеевич', lastName: 'Куроносов', age: 2},
  { name: 'Артем', secondName: 'Сергеевич', lastName: 'Погосян', age: 29},
  { name: 'Елизавета', secondName: 'Анатольевна', lastName: 'Романова', age: 43},
  { name: 'Елена', secondName: 'Алексеевна', lastName: 'Анина', age: 43},
  { name: 'Артем', secondName: 'Алексеевич', lastName: 'Петров', age: 29},
  { name: 'Екатерина', secondName: 'Алексеевна', lastName: 'Попова', age: 43}
]